//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_log
    {
        public int id { get; set; }
        public Nullable<System.DateTime> change_date { get; set; }
        public Nullable<int> id_client { get; set; }
        public string client_info { get; set; }
        public string client_status { get; set; }
    }
}
