//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID_request { get; set; }
        public System.DateTime data_request { get; set; }
        public int manager { get; set; }
        public Nullable<int> client_firm { get; set; }
        public Nullable<int> client { get; set; }
        public int article_software { get; set; }
        public Nullable<double> regular_price { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<double> result_price { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual Client_firm Client_firm1 { get; set; }
        public virtual Manager Manager1 { get; set; }
        public virtual Price_software Price_software { get; set; }
    }
}
