//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Manager
    {
        public int ID_manager { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string login_manager { get; set; }
        public string password_manager { get; set; }
        public string phone { get; set; }
        public string e_mail { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string number_house { get; set; }
        public Nullable<int> number_flat { get; set; }
    }
}
