//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Client_firm
    {
        public int ID_firm { get; set; }
        public string name_firm { get; set; }
        public string VAT { get; set; }
        public string last_name_confidant { get; set; }
        public string first_name_confidant { get; set; }
        public string phone { get; set; }
        public string e_mail { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string number_house { get; set; }
        public Nullable<int> number_room { get; set; }
    }
}
